# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SplashWallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SplashWallet
  
  
  pod 'MaterialComponents/BottomSheet'
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/Tabs+TabBarView'
  pod 'MaterialComponents/Typography'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end

end
